---
version: v3
services:

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plefi
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  mitm:
    image: mitmproxy/mitmproxy
    tty: true
    ports:
      - 8888:8080
      - 8081:8081
    command: mitmweb --web-host 0.0.0.0
